apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ deployment.namespace }}
  name: glance-post
spec:
  template:
    metadata:
      namespace: {{ deployment.namespace }}
      name: glance-post
    spec:
      restartPolicy: OnFailure
      # TODO(DTadrzak): it must be removed in future
      securityContext:
        runAsUser: 0
      containers:
        - name: glance-post
          image: {{ deployment.image.post }}
          imagePullPolicy: Always
          # TODO(DTadrzak): it must be removed in future
          securityContext:
            privileged: true
          env:
            - name: INTERFACE_NAME
              value: "eth0"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: COMMAND
              value: "bash /tmp/post.sh"
            - name: DEPENDENCY_SERVICE
              value: "keystone-api,glance-api,glance-registry"
            - name: DEPENDENCY_CONFIG
              value: "/tmp/post.sh"
            - name: ANSIBLE_LIBRARY
              value: /usr/share/ansible/
          volumeMounts:
            - name: postsh
              mountPath: /configmaps/post.sh
      volumes:
        - name: postsh
          configMap:
            name: glance-postsh
