apiVersion: extensions/v1beta1
kind: Deployment
spec:
  replicas: {{ deployment.replicas }}
  template:
    metadata:
      labels:
        app: neutron-agents
    spec:
      nodeSelector:
        {{ deployment.node_label }}: enabled
      securityContext:
        runAsUser: 0
      dnsPolicy: ClusterFirst
      hostNetwork: true
      containers:
        - name: neutron-dhcp-agent
          image: {{ deployment.image.dhcp }}
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: INTERFACE_NAME
              value: {{ network.minion_interface_name }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: COMMAND
              value: "neutron-dhcp-agent --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/dhcp-agent.ini"
            - name: DEPENDENCY_JOBS
              value: "neutron-init,nova-post"
            - name: DEPENDENCY_SERVICE
              value: "neutron-server,rabbitmq,nova-api"
            - name: DEPENDENCY_CONFIG
              value: "/etc/neutron/neutron.conf,/etc/neutron/plugins/ml2/ml2-conf.ini,/etc/neutron/dhcp-agent.ini,/etc/neutron/dnsmasq.conf,/etc/resolv.conf,/etc/hosts"
          ports:
          volumeMounts:
            - name: neutronconf
              mountPath: /configmaps/neutron.conf
            - name: ml2confini
              mountPath: /configmaps/ml2-conf.ini
            - name: dhcpagentini
              mountPath: /configmaps/dhcp-agent.ini
            - name: dnsmasqconf
              mountPath: /configmaps/dnsmasq.conf
            - name: resolvconf
              mountPath: /configmaps/resolv.conf
            - name: hosts
              mountPath: /configmaps/hosts
            - name: libmodules
              mountPath: /lib/modules
              readOnly: true
            - name: runopenvswitch
              mountPath: /run/openvswitch
            - name: usrsbinip
              mountPath: /usr/sbin/ip
            - name: socket
              mountPath: /var/lib/neutron/kolla/
        - name: neutron-l3-agent
          image: {{ deployment.image.l3 }}
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: INTERFACE_NAME
              value: {{ network.minion_interface_name }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: COMMAND
              value: "neutron-l3-agent --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/l3-agent.ini --config-file /etc/neutron/plugins/ml2/ml2-conf.ini"
            - name: DEPENDENCY_JOBS
              value: "nova-init,neutron-init,nova-post"
            - name: DEPENDENCY_SERVICE
              value: "neutron-server,rabbitmq,nova-api"
            - name: DEPENDENCY_CONFIG
              value: "/etc/neutron/neutron.conf,/etc/neutron/plugins/ml2/ml2-conf.ini,/etc/neutron/l3-agent.ini,/etc/resolv.conf"
          volumeMounts:
            - name: neutronconf
              mountPath: /configmaps/neutron.conf
            - name: ml2confini
              mountPath: /configmaps/ml2-conf.ini
            - name: l3agentini
              mountPath: /configmaps/l3-agent.ini
            - name: resolvconf
              mountPath: /configmaps/resolv.conf
            - name: libmodules
              mountPath: /lib/modules
              readOnly: true
            - name: runopenvswitch
              mountPath: /run/openvswitch
            - name: usrsbinip
              mountPath: /usr/sbin/ip
            - name: socket
              mountPath: /var/lib/neutron/kolla/
      volumes:
        - name: neutronconf
          configMap:
            name: neutron-neutronconf
        - name: ml2confini
          configMap:
            name: neutron-ml2confini
        - name: dhcpagentini
          configMap:
            name: neutron-dhcpagentini
        - name: dnsmasqconf
          configMap:
            name: neutron-dnsmasqconf
        - name: resolvconf
          configMap:
            name: neutron-resolvconf
        - name: hosts
          configMap:
            name: neutron-hosts
        - name: l3agentini
          configMap:
            name: neutron-l3agentini
        - name: libmodules
          hostPath:
            path: /lib/modules
        - name: runopenvswitch
          hostPath:
            path: /run/openvswitch
        - name: usrsbinip
          hostPath:
            path: /usr/bin/ip
        - name: socket
          hostPath:
            path: /var/lib/neutron/kolla/
