deployment:
  # Underlying container runtime to use.
  engine: docker
  # Number of replicas of HA services to deploy.
  control_replicas: 1
  compute_replicas: 1
  # Labels of the nodes on which services are deployed.
  control_node_label: "openstack-control-plane"
  compute_node_label: "openstack-compute-node"
  image:
    # Base path for container images.
    # '%s' is replaced by the application name.
    base: "quay.io/stackanetes/stackanetes-%s:newton"

network:
  # Network interface name on the Kubernetes nodes.
  minion_interface_name: "eno1"
  # List of IPs of Kubernetes nodes that may be used
  # to expose externally certain services when Ingress
  # is disabled (i.e. Horizon, nova-novncproxy).
  external_ips: []
  dns:
    # List of DNS servers to use for services that use
    # the host network (i.e. Neutron, OpenvSwitch, nova-compute).
    # This typically includes the Kubernetes cluster DNS and a
    # DNS server that is able to resolve Kubernetes nodes.
    servers:
      - 10.3.0.10
    # Kubernetes domain name.
    kubernetes_domain: cluster.local
    # Any other domains to be included for DNS resolution.
    other_domains:
  ingress:
    # Whether or not external access to OpenStack APIs
    # should be possible using simple domains.
    # Modifying this after the initial deployment
    # requires to manually override the Keystone endpoints.
    enabled: true
    # Base path and port for external access.
    # '%s' is replaced by the service name.
    # Modifying this after the initial deployment
    # requires to manually override the Keystone endpoints.
    host: "%s.openstack.cluster"
    port: 30080

ceph:
  # Whether or not Ceph should be used.
  enabled: false
  # List of monitors to use.
  monitors: []
  # Users, keyrings and pools to use.
  cinder_user: "cinder"
  cinder_pool: "volumes"
  cinder_keyring: ""
  glance_user: "glance"
  glance_pool: "images"
  glance_keyring: ""
  nova_pool: "vms"
  # Random uuid used for Nova / Cinder communication.
  # Should not be modified after the initial deployment.
  secret_uuid: bbc5b4d5-6fca-407d-807d-06a4f4a7bccb

neutron:
  metadata_secret: password

rabbitmq:
  admin_password: password
  erlang_cookie: "ERLANG_COOKIE"

database:
  root_password: password
  keystone_password: password
  cinder_password: password
  glance_password: password
  neutron_password: password
  nova_password: password

keystone:
  admin_password: password
  cinder_password: password
  glance_password: password
  neutron_password: password
  nova_password: password

misc:
  workers: 8
  debug: false

# It is possible to override parameters for specific
# depencendies too.
# stackanetes/neutron:
#   misc:
#     debug: true
