deployment:
  replicas: 1
  image:
    base: "quay.io/stackanetes/stackanetes-%s:barcelona"

network:
  minion_interface_name: eno1
  external_ips: []
  dns:
    ip: 10.3.0.10
    kubernetes_domain: cluster.local
    infra_domain:
  ingress:
    enabled: true
    host: "%s.openstack.cluster"
    port: 30080

ceph:
  enabled: true
  monitors: []
  cinder_user: "cinder"
  cinder_pool: "volumes"
  cinder_keyring: ""
  glance_user: "glance"
  glance_pool: "images"
  glance_keyring: ""
  nova_pool: "vms"
  rgw_user: rgw
  rgw_keyring: ""
  secret_uuid: secret
  secret_uuid: bbc5b4d5-6fca-407d-807d-06a4f4a7bccb

neutron:
  metadata_secret: password

rabbitmq:
  admin_password: password
  erlang_cookie: "ERLANG_COOKIE"

database:
  root_password: password
  keystone_password: password
  cinder_password: password
  glance_password: password
  neutron_password: password
  nova_password: password

keystone:
  admin_password: password
  cinder_password: password
  glance_password: password
  neutron_password: password
  nova_password: password

misc:
  workers: 8
  debug: false

# Single dependency's parameters can also be overriden:
# stackanetes/neutron:
#   misc:
#     debug: true
